
export { books };
const books = [
    {
        id: 1,
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        rating: 4.5,
        genre: "fiction",
    },
    {
        id: 2,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        rating: 4.8,
        genre: "fiction",
    },
    {
        id: 3,
        title: "1984",
        author: "George Orwell",
        rating: 4.7,
        genre: "fiction",
    },
    {
        id: 4,
        title: "Brave New World",
        author: "Aldous Huxley",
        rating: 4.6,
        genre: "science",
    },
    {
        id: 5,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        rating: 4.3,
        genre: "fiction",
    },
    {
        id: 6,
        title: "Pride and Prejudice",
        author: "Jane Austen",
        rating: 4.9,
        genre: "romance",
    },
    {
        id: 7,
        title: "The Fault in Our Stars",
        author: "John Green",
        rating: 4.9,
        genre: "romance",
    },
    {
        id: 8,
        title: "The Time Traveler's Wife",
        author: "Audrey Niffenegger",
        rating: 4.5,
        genre: "romance",
    },
    {
        id: 9,
        title: "A Brief History of Time",
        author: "Stephen Hawking",
        rating: 4.7,
        genre: "science",
    },
    {
        id: 10,
        title: "The Theory of Everything",
        author: "Stephen Hawking",
        rating: 4.6,
        genre: "science",
    },
    {
        id: 11,
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        rating: 4.7,
        genre: "fiction",
    },
    {
        id: 12,
        title: "The Lord of the Rings",
        author: "J.R.R. Tolkien",
        rating: 4.9,
        genre: "fiction",
    },
    {
        id: 13,
        title: "Wuthering Heights",
        author: "Emily Brontë",
        rating: 4.6,
        genre: "romance",
    },
    {
        id: 14,
        title: "Dune",
        author: "Frank Herbert",
        rating: 4.8,
        genre: "science",
    },
    {
        id: 15,
        title: "The Hunger Games",
        author: "Suzanne Collins",
        rating: 4.5,
        genre: "fiction",
    },
    {
        id: 16,
        title: "The Alchemist",
        author: "Paulo Coelho",
        rating: 4.8,
        genre: "fiction",
    },
    {
        id: 17,
        title: "The Notebook",
        author: "Nicholas Sparks",
        rating: 4.4,
        genre: "romance",
    },
    {
        id: 18,
        title: "Fifty Shades of Grey",
        author: "E.L. James",
        rating: 4.2,
        genre: "romance",
    },
    {
        id: 19,
        title: "The Martian",
        author: "Andy Weir",
        rating: 4.8,
        genre: "science",
    },
    {
        id: 20,
        title: "A Wrinkle in Time",
        author: "Madeleine L'Engle",
        rating: 4.6,
        genre: "science",
    },
];


